### ISSUE TITLE
Celsius/Farenheit behavior clarification

### ISSUE THREAD

**Issue by anxolerd** [snipter/firebase-iot-codelab#3]
I'd like to clarify about DHT library which is used in this codelab.

Following the [temperature sensor guide](https://github.com/snipter/firebase-iot-codelab/blob/master/docs/en/03-temperature-and-humidity-sensor.md) I noticed that by default we read the temperature in Celsius and have to pass an additional boolean flag in order to retrieve temperature in Farenheit.

However while calculating heat index by default it is assumed that temperature is in Farenheit, and in order to calculate it for Celsius we need to pass an additional flag.

Do you have any idea about why the API is designed that way? (mb some hardware internals requre that, etc?)

Thanks in advance

**Comment by husky-dev** [comment]
You can checkout source file of this library. It's quite simple. This source file shows that there is no some special hardware dependencies. Just in case of flag equal to `true` library makes a conversion from one measurement system to the another.

https://github.com/adafruit/DHT-sensor-library/blob/master/DHT.cpp

I'm agree with you that it's strange. It's will be much better to just have one default measurement system. You can send pull request to the author of the lib. But they can reject you pull cos afraid breaking backward compatibility. 

I can add this library right to the sources of the starter projects in this repo. But I don't wanna cos I want people to try to use PlatformIO's package manager.

**Comment by anxolerd** [comment]
Thanks for the clarification. I saw the library sources but thought that it is rather me who does not understand something than a reasonless weirdness of the API.

I think I am going to make a PR into library, hope they (as well as Platform is) use semver, so breaking changes will not affect those who use older major versions.
